


interface ITypes {
    FILTER_CONTACTS: 'FILTER_CONTACTS',
    GET_ONE_CONTACT: 'GET_ONE_CONTACT',
    GET_ONE_CONTACT_GROUP : 'GET_ONE_CONTACTS_GROUP'
}


export const types: ITypes =  {
    FILTER_CONTACTS: 'FILTER_CONTACTS',
    GET_ONE_CONTACT: 'GET_ONE_CONTACT',
    GET_ONE_CONTACT_GROUP : 'GET_ONE_CONTACTS_GROUP'
}